 
		

		package com.univeris.cxp.workflows;
			
		
	

	
	
	import java.util.ArrayList;
	import java.util.List;
	import java.util.Date;



		
		
	


		
	
	/**
	 * This file is an Entity Class generated by Witchcraftmda.
	 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
	 */
	

	

	
	

	public class questionnaireFlow extends questionnaireFlowBase implements java.io.Serializable {
		private static final long serialVersionUID = 1095017273L;
	}

	